# Generated by Django 4.0.3 on 2022-03-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntunkoroge', '0002_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=222, null=True, unique=True),
        ),
    ]
